#!/bin/sh

CDPATH=""
SCRIPT="$0"

# SCRIPT may be an arbitrarily deep series of symlinks. Loop until we have the concrete path.
while [ -h "$SCRIPT" ] ; do
  ls=`ls -ld "$SCRIPT"`
  # Drop everything prior to ->
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    SCRIPT="$link"
  else
    SCRIPT=`dirname "$SCRIPT"`/"$link"
  fi
done

# determine fscrawler home
FS_HOME=`dirname "$SCRIPT"`/..

# make FS_HOME absolute
FS_HOME=`cd "$FS_HOME"; pwd`
FS_CLASSPATH="$FS_HOME/lib/*"

if [ -x "$JAVA_HOME/bin/java" ]; then
    JAVA="$JAVA_HOME/bin/java"
else
    JAVA=`which java`
fi

if [ ! -x "$JAVA" ]; then
    echo "Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME"
    exit 1
fi

# set to headless, just in case
JAVA_OPTS="$JAVA_OPTS -Djava.awt.headless=true"

# Ensure UTF-8 encoding by default (e.g. filenames)
JAVA_OPTS="$JAVA_OPTS -Dfile.encoding=UTF-8"
JAVA_OPTS="$JAVA_OPTS -Dsun.jnu.encoding=UTF-8"

# Use LOG4J2 instead of java.util.logging
JAVA_OPTS="$JAVA_OPTS -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager"

# Define LOG4J2 config file (if running in background, we will use log4j2-file)
case $(ps -o stat= -p $$) in
  *+*) JAVA_OPTS="$JAVA_OPTS -Dlog4j.configurationFile=$FS_HOME/config/log4j2.xml" ;;
  *) JAVA_OPTS="$JAVA_OPTS -Dlog4j.configurationFile=$FS_HOME/config/log4j2-file.xml" ;;
esac

# Fix for CVE-2021-44228
JAVA_OPTS="$JAVA_OPTS -Dlog4j2.formatMsgNoLookups=true"

# If the user defined FS_JAVA_OPTS, we will use it to start the crawler
JAVA_OPTS="$JAVA_OPTS $FS_JAVA_OPTS"

exec "$JAVA" ${JAVA_OPTS} -cp "$FS_CLASSPATH" "${distribution.mainClassName}" "$@"
