name-template: 'fscrawler-$RESOLVED_VERSION'
tag-template: 'fscrawler-$RESOLVED_VERSION'
categories:
  - title: 🚀 New features
    label: new
  - title: 🚨 Bug Fixes
    label: bug
  - title: 💉 Updated features
    label: update
  - title: 🧹 Cleaned or removed features
    label: remove
  - title: 📝 Documentation updates
    label: doc
  - title: 🚦 Tests
    label: test
change-template: '- #$NUMBER: $TITLE (thanks to @$AUTHOR)'
template: |

  $CHANGES

  ## Thanks to

  $CONTRIBUTORS
