FROM eclipse-temurin:25-jre

ARG langsPkg

RUN set -ex \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    procps \
    curl \
    ${langsPkg} \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY maven /usr/share/fscrawler
ENTRYPOINT [ "/usr/share/fscrawler/bin/fscrawler" ]
