blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://discuss.elastic.co/c/elasticsearch
    about: Ask (and answer) questions here. Use fscrawler anywhere in the text as it is monitored.
